### ISSUE TITLE
Missing line in ibm/isam/roles/set_ldap_root_pw/tasks/main.yml

### ISSUE THREAD

**Issue by Franclaf7** [IBM-Security/isam-ansible-collection#107]
Missing the first "- name: " line in ibm/isam/roles/set_ldap_root_pw/tasks/main.yml:

`  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.web.embedded_ldap.admin.set_pw
    isamapi:
  notify: Commit Changes
`

**ERROR! The tasks/main.yml file for role 'set_ldap_root_pw' must contain a list of tasks**

Also missing the "**password**" parameter for the isamapi call.

**Comment by tombosmansibm** [comment]
Ansible-lint can now run without crashing.  This should fix this issue.

**Comment by Franclaf7** [comment]
For some reason, I'm having problems with my local Git and I can't seem to update my forked repo to push a PR.

Anyways, this issue should still be opened because the "_password: "{{ set_ldap_root_pw_password }}"_" is still missing for the isamapi call.

Sorry for the late answer.
